**Series in Panda**

In [66]:
import numpy as np
import pandas as pd

In [67]:
labels = ['a','b','c']
list = [10,20,30]
arr = np.array([10,20,30])
dic = {1:20,2:20,3:30}

In [68]:
pd.Series(list)

0    10
1    20
2    30
dtype: int64

In [69]:
pd.Series(list,index=labels)

a    10
b    20
c    30
dtype: int64

In [70]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [71]:
pd.Series(arr,index=list)

10    10
20    20
30    30
dtype: int64

In [72]:
pd.Series(dic)

1    20
2    20
3    30
dtype: int64

In [73]:
data = {
    'name' : ['bhavik','savan','parth','lav'],
    'age' :[19,18,17,19],
    'city' : ['ahemdabad','gandhinagr','maninagar','anand'],
    'salary':[10000,5000,2000,4000]
}
df = pd.DataFrame(data)

In [74]:
data_list = [
    ['bhavik',19,'ahemdabad',10000],
    ['savan',18,'gandhinagr',5000],
     ['parth',17,'maninagar',2000],
    ['lav',19,'anand',4000]
]
df2 = pd.DataFrame(data_list)
columns = ['name','age','city','salary']
df2 = pd.DataFrame(data_list,columns=columns)

In [75]:
df2

     name  age        city  salary
0  bhavik   19   ahemdabad   10000
1   savan   18  gandhinagr    5000
2   parth   17   maninagar    2000
3     lav   19       anand    4000

**Selection and indexing **

In [76]:
df2[['name','city']]

     name        city
0  bhavik   ahemdabad
1   savan  gandhinagr
2   parth   maninagar
3     lav       anand

In [77]:
df2["id"]= ["01","02","03","04"]

In [78]:
df2

     name  age        city  salary  id
0  bhavik   19   ahemdabad   10000  01
1   savan   18  gandhinagr    5000  02
2   parth   17   maninagar    2000  03
3     lav   19       anand    4000  04

In [79]:
df2.drop("id",axis=1,inplace=True)

In [80]:
df2

     name  age        city  salary
0  bhavik   19   ahemdabad   10000
1   savan   18  gandhinagr    5000
2   parth   17   maninagar    2000
3     lav   19       anand    4000

In [81]:
df2.drop(0,axis=0)

    name  age        city  salary
1  savan   18  gandhinagr    5000
2  parth   17   maninagar    2000
3    lav   19       anand    4000

In [82]:
df2

     name  age        city  salary
0  bhavik   19   ahemdabad   10000
1   savan   18  gandhinagr    5000
2   parth   17   maninagar    2000
3     lav   19       anand    4000

In [83]:
df2.loc[1]

name           savan
age               18
city      gandhinagr
salary          5000
Name: 1, dtype: object

In [84]:
df.iloc[3]

name        lav
age          19
city      anand
salary     4000
Name: 3, dtype: object

In [85]:
df.loc[[0,1]][["city","salary"]]

         city  salary
0   ahemdabad   10000
1  gandhinagr    5000

In [86]:
df.loc[[2,3]][["name","age"]]

    name  age
2  parth   17
3    lav   19

In [87]:
df2[df2["age"]>18]

     name  age       city  salary
0  bhavik   19  ahemdabad   10000
3     lav   19      anand    4000

In [89]:
df2[(df2["age"]>18) & (df2["salary"]==4000)]

  name  age   city  salary
3  lav   19  anand    4000