**Series in Panda**

In [181]:
import numpy as np
import pandas as pd

In [182]:
labels = ['a','b','c']
list = [10,20,30]
arr = np.array([10,20,30])
dic = {1:20,2:20,3:30}

In [183]:
pd.Series(list)

0    10
1    20
2    30
dtype: int64

In [184]:
pd.Series(list,index=labels)

a    10
b    20
c    30
dtype: int64

In [185]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [186]:
pd.Series(arr,index=list)

10    10
20    20
30    30
dtype: int64

In [187]:
pd.Series(dic)

1    20
2    20
3    30
dtype: int64

In [188]:
data = {
    'name' : ['bhavik','savan','parth','lav'],
    'age' :[19,18,17,19],
    'city' : ['ahemdabad','gandhinagr','maninagar','anand'],
    'salary':[10000,5000,2000,4000]
}
df3 = pd.DataFrame(data)

In [189]:
data_list = [
    ['bhavik',19,'ahemdabad',10000],
    ['savan',18,'gandhinagr',5000],
     ['parth',17,'maninagar',2000],
    ['lav',19,'anand',4000]
]
df2 = pd.DataFrame(data_list)
columns = ['name','age','city','salary']
df2 = pd.DataFrame(data_list,columns=columns)

In [190]:
df2

     name  age        city  salary
0  bhavik   19   ahemdabad   10000
1   savan   18  gandhinagr    5000
2   parth   17   maninagar    2000
3     lav   19       anand    4000

**Selection and indexing **

In [191]:
df2[['name','city']]

     name        city
0  bhavik   ahemdabad
1   savan  gandhinagr
2   parth   maninagar
3     lav       anand

In [192]:
df2["id"]= ["01","02","03","04"]

In [193]:
df2

     name  age        city  salary  id
0  bhavik   19   ahemdabad   10000  01
1   savan   18  gandhinagr    5000  02
2   parth   17   maninagar    2000  03
3     lav   19       anand    4000  04

In [194]:
df2.drop("id",axis=1,inplace=True)

In [195]:
df2

     name  age        city  salary
0  bhavik   19   ahemdabad   10000
1   savan   18  gandhinagr    5000
2   parth   17   maninagar    2000
3     lav   19       anand    4000

In [196]:
df2.drop(0,axis=0)

    name  age        city  salary
1  savan   18  gandhinagr    5000
2  parth   17   maninagar    2000
3    lav   19       anand    4000

In [197]:
df2

     name  age        city  salary
0  bhavik   19   ahemdabad   10000
1   savan   18  gandhinagr    5000
2   parth   17   maninagar    2000
3     lav   19       anand    4000

In [198]:
df2.loc[1]

name           savan
age               18
city      gandhinagr
salary          5000
Name: 1, dtype: object

In [199]:
df.iloc[3]

A    4.0
B    4.0
C    NaN
D    NaN
Name: 3, dtype: float64

In [200]:
df3.loc[[0,1]][["city","salary"]]

         city  salary
0   ahemdabad   10000
1  gandhinagr    5000

In [201]:
df3.loc[[2,3]][["name","age"]]

    name  age
2  parth   17
3    lav   19

In [202]:
df2[df2["age"]>18]

     name  age       city  salary
0  bhavik   19  ahemdabad   10000
3     lav   19      anand    4000

In [203]:
df2[(df2["age"]>18) & (df2["salary"]==4000)]

  name  age   city  salary
3  lav   19  anand    4000

In [204]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [205]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [206]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [207]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [208]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

Removing Missingdata

In [209]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [210]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [211]:
df.dropna(thresh=4)

     A  B    C    D
0  1.0  1  1.0  1.0

Filling Missing Data

In [212]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [214]:
values = {'A':400,'B':100,'C':200,'D':300}
df.fillna(value=values)

       A  B      C      D
0    1.0  1    1.0    1.0
1    2.0  2    2.0  300.0
2  400.0  3    3.0  300.0
3    4.0  4  200.0  300.0
4    5.0  5  200.0    5.0

In [215]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

**MarginJoiningconcatination**

In [216]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [217]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [218]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [223]:
pd.merge(employees,salaries,on="employee_id",how="inner")

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [225]:
pd.merge(employees,salaries,on="employee_id",how="outer")

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [226]:
pd.merge(employees,salaries,on="employee_id",how="left")

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [227]:
pd.merge(employees,salaries,on="employee_id",how="right")

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

Concatination of 2 dataframes

In [228]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [230]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [231]:
pd.concat([df1,df2],axis = 1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

Joining Data

In [232]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [233]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [234]:
df2

   score
2     85
3     90
4     75

In [237]:
df1.join(df2,how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

**GroupBy**

In [238]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [239]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [245]:
a = df.groupby('Category')['Sales'].sum()
a

Category
A    570
B    930
Name: Sales, dtype: int64

In [246]:
a = df.groupby('Store')['Sales'].sum()
a

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [248]:
a = df.groupby(['Category','Store'])['Sales'].sum()
a

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

**Aggregation**

In [250]:
df['Sales'].mean()

np.float64(187.5)

In [253]:
df['Sales'].min()

100

In [254]:
df['Sales'].max()

300

In [255]:
df['Sales'].median()

190.0

In [256]:
df['Sales'].std()

66.06274074155351

In [257]:
df['Sales'].count()

np.int64(8)

In [261]:
df['Sales'].mode()

0    200
Name: Sales, dtype: int64

In [263]:
df['Sales'].agg(['mean','min','max','median','std','count'])

mean      187.500000
min       100.000000
max       300.000000
median    190.000000
std        66.062741
count       8.000000
Name: Sales, dtype: float64

**Pivot Tables**

In [264]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    578     72   John  January      Q1
1  2023-01-02       B   West    203     33   Mary  January      Q1
2  2023-01-03       C  North    842     38    Bob  January      Q1
3  2023-01-04       D  South    444     75  Alice  January      Q1
4  2023-01-05       A   East    747     48   John  January      Q1
5  2023-01-06       B   West    760     40   Mary  January      Q1
6  2023-01-07       C  North    357     81    Bob  January      Q1
7  2023-01-08       D  South    397     66  Alice  January      Q1
8  2023-01-09       A   East    986     37   John  January      Q1
9  2023-01-10       B   West    619     97   Mary  January      Q1
10 2023-01-11       C  North    774     54    Bob  January      Q1
11 2023-01-12       D  South    889     45  Alice  January      Q1
12 2023-01-13       A   East    737     73   John  January      Q1
13 2023-01-14       B   West    362     53   Mary  January      Q1
14 2023-01-15       C  North    733     27    Bob  January      Q1
15 2023-01-16       D  South    519     45  Alice  January      Q1
16 2023-01-17       A   East    105     88   John  January      Q1
17 2023-01-18       B   West    905     74   Mary  January      Q1
18 2023-01-19       C  North    833     49    Bob  January      Q1
19 2023-01-20       D  South    892     36  Alice  January      Q1

In [270]:
from ast import Index
pd.pivot_table(df,values="Sales",index='Region',columns="Product",aggfunc='sum')

Product       A       B       C       D
Region
East     3153.0     NaN     NaN     NaN
North       NaN     NaN  3539.0     NaN
South       NaN     NaN     NaN  3141.0
West        NaN  2849.0     NaN     NaN

In [271]:
 pivot2 = pd.pivot_table(df, values=['Sales', 'Units'], index='Region', columns='Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     630.6    NaN    NaN    NaN  63.6   NaN   NaN   NaN
North      NaN    NaN  707.8    NaN   NaN   NaN  49.8   NaN
South      NaN    NaN    NaN  628.2   NaN   NaN   NaN  53.4
West       NaN  569.8    NaN    NaN   NaN  59.4   NaN   NaN

**Cross Tabs**

In [272]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

**Operations**

In [274]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [276]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [277]:
df1.shape

(5, 3)

In [278]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [279]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [282]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [284]:
df1['A']+20

0    21
1    22
2    23
3    24
4    25
Name: A, dtype: int64

In [285]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [286]:
def square(x):
  return x**2

In [290]:
df1["D"]=df1["B"].apply(square)

In [291]:
df1

   A     B    C        D
0  1   100  100    10000
1  2   400  200   160000
2  3   900  300   810000
3  4  1600  400  2560000
4  5  2500  500  6250000